// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v5.27.1
// source: service.proto

package guider

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetItemsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (x *GetItemsReq) Reset() {
	*x = GetItemsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetItemsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsReq) ProtoMessage() {}

func (x *GetItemsReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsReq.ProtoReflect.Descriptor instead.
func (*GetItemsReq) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetItemsReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

//  响应结构
type GetItemResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuiderItems []*GuiderItem `protobuf:"bytes,1,rep,name=guiderItems,proto3" json:"guiderItems,omitempty"`
}

func (x *GetItemResp) Reset() {
	*x = GetItemResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetItemResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemResp) ProtoMessage() {}

func (x *GetItemResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemResp.ProtoReflect.Descriptor instead.
func (*GetItemResp) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetItemResp) GetGuiderItems() []*GuiderItem {
	if x != nil {
		return x.GuiderItems
	}
	return nil
}

type GetSymbolConfigReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PortfolioId string `protobuf:"bytes,1,opt,name=portfolioId,proto3" json:"portfolioId,omitempty"`
	Pair        string `protobuf:"bytes,2,opt,name=pair,proto3" json:"pair,omitempty"`
}

func (x *GetSymbolConfigReq) Reset() {
	*x = GetSymbolConfigReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSymbolConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSymbolConfigReq) ProtoMessage() {}

func (x *GetSymbolConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSymbolConfigReq.ProtoReflect.Descriptor instead.
func (*GetSymbolConfigReq) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetSymbolConfigReq) GetPortfolioId() string {
	if x != nil {
		return x.PortfolioId
	}
	return ""
}

func (x *GetSymbolConfigReq) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

//  响应结构
type GetSymbolConfigResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SymbolConfig *GuiderSymbolConfig `protobuf:"bytes,1,opt,name=symbolConfig,proto3" json:"symbolConfig,omitempty"`
}

func (x *GetSymbolConfigResp) Reset() {
	*x = GetSymbolConfigResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSymbolConfigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSymbolConfigResp) ProtoMessage() {}

func (x *GetSymbolConfigResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSymbolConfigResp.ProtoReflect.Descriptor instead.
func (*GetSymbolConfigResp) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetSymbolConfigResp) GetSymbolConfig() *GuiderSymbolConfig {
	if x != nil {
		return x.SymbolConfig
	}
	return nil
}

type GetPositionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PortfolioId string `protobuf:"bytes,1,opt,name=portfolioId,proto3" json:"portfolioId,omitempty"`
}

func (x *GetPositionReq) Reset() {
	*x = GetPositionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPositionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionReq) ProtoMessage() {}

func (x *GetPositionReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionReq.ProtoReflect.Descriptor instead.
func (*GetPositionReq) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetPositionReq) GetPortfolioId() string {
	if x != nil {
		return x.PortfolioId
	}
	return ""
}

//  响应结构
type GetPositionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Positions []*GuiderPosition `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
}

func (x *GetPositionResp) Reset() {
	*x = GetPositionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPositionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionResp) ProtoMessage() {}

func (x *GetPositionResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionResp.ProtoReflect.Descriptor instead.
func (*GetPositionResp) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetPositionResp) GetPositions() []*GuiderPosition {
	if x != nil {
		return x.Positions
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

var file_service_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x1e, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x6c, 0x6f, 0x6f, 0x6c, 0x69, 0x73, 0x68, 0x6d, 0x61, 0x6e,
	0x2e, 0x67, 0x75, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a,
	0x0c, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x5a, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x4b, 0x0a, 0x0b, 0x67, 0x75, 0x69, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x6c,
	0x6f, 0x6f, 0x6c, 0x69, 0x73, 0x68, 0x6d, 0x61, 0x6e, 0x2e, 0x67, 0x75, 0x69, 0x64, 0x65, 0x72,
	0x2e, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x47, 0x75, 0x69, 0x64, 0x65, 0x72, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x0b, 0x67, 0x75, 0x69, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22,
	0x4a, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c,
	0x69, 0x6f, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x6f, 0x72, 0x74,
	0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x69, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x69, 0x72, 0x22, 0x6c, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x55, 0x0a, 0x0c, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x66,
	0x6c, 0x6f, 0x6f, 0x6c, 0x69, 0x73, 0x68, 0x6d, 0x61, 0x6e, 0x2e, 0x67, 0x75, 0x69, 0x64, 0x65,
	0x72, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x47, 0x75, 0x69, 0x64, 0x65, 0x72, 0x53,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x0c, 0x73, 0x79, 0x6d,
	0x62, 0x6f, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x32, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x70,
	0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x49, 0x64, 0x22, 0x5e, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x4b, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x6c, 0x6f, 0x6f, 0x6c, 0x69,
	0x73, 0x68, 0x6d, 0x61, 0x6e, 0x2e, 0x67, 0x75, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x2e, 0x47, 0x75, 0x69, 0x64, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x32, 0xc6, 0x03,
	0x0a, 0x0d, 0x47, 0x75, 0x69, 0x64, 0x65, 0x72, 0x57, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x12,
	0x66, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x2b, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x66, 0x6c, 0x6f, 0x6f, 0x6c, 0x69, 0x73, 0x68, 0x6d, 0x61, 0x6e, 0x2e, 0x67, 0x75,
	0x69, 0x64, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x2b, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x66,
	0x6c, 0x6f, 0x6f, 0x6c, 0x69, 0x73, 0x68, 0x6d, 0x61, 0x6e, 0x2e, 0x67, 0x75, 0x69, 0x64, 0x65,
	0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x7c, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x32, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x66, 0x6c, 0x6f, 0x6f, 0x6c, 0x69, 0x73, 0x68, 0x6d, 0x61, 0x6e, 0x2e, 0x67, 0x75, 0x69,
	0x64, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x33,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x6c, 0x6f, 0x6f, 0x6c, 0x69, 0x73, 0x68, 0x6d, 0x61, 0x6e,
	0x2e, 0x67, 0x75, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x71, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2e, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x6c, 0x6f, 0x6f,
	0x6c, 0x69, 0x73, 0x68, 0x6d, 0x61, 0x6e, 0x2e, 0x67, 0x75, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x2f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x6c, 0x6f, 0x6f,
	0x6c, 0x69, 0x73, 0x68, 0x6d, 0x61, 0x6e, 0x2e, 0x67, 0x75, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x2f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x6c, 0x6f, 0x6f, 0x6c, 0x69,
	0x73, 0x68, 0x6d, 0x61, 0x6e, 0x2e, 0x67, 0x75, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x70, 0x62, 0x73, 0x2f,
	0x67, 0x75, 0x69, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData = file_service_proto_rawDesc
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_proto_rawDescData)
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_service_proto_goTypes = []interface{}{
	(*GetItemsReq)(nil),         // 0: com.floolishman.guider.service.GetItemsReq
	(*GetItemResp)(nil),         // 1: com.floolishman.guider.service.GetItemResp
	(*GetSymbolConfigReq)(nil),  // 2: com.floolishman.guider.service.GetSymbolConfigReq
	(*GetSymbolConfigResp)(nil), // 3: com.floolishman.guider.service.GetSymbolConfigResp
	(*GetPositionReq)(nil),      // 4: com.floolishman.guider.service.GetPositionReq
	(*GetPositionResp)(nil),     // 5: com.floolishman.guider.service.GetPositionResp
	(*GuiderItem)(nil),          // 6: com.floolishman.guider.params.GuiderItem
	(*GuiderSymbolConfig)(nil),  // 7: com.floolishman.guider.params.GuiderSymbolConfig
	(*GuiderPosition)(nil),      // 8: com.floolishman.guider.params.GuiderPosition
	(*emptypb.Empty)(nil),       // 9: google.protobuf.Empty
}
var file_service_proto_depIdxs = []int32{
	6, // 0: com.floolishman.guider.service.GetItemResp.guiderItems:type_name -> com.floolishman.guider.params.GuiderItem
	7, // 1: com.floolishman.guider.service.GetSymbolConfigResp.symbolConfig:type_name -> com.floolishman.guider.params.GuiderSymbolConfig
	8, // 2: com.floolishman.guider.service.GetPositionResp.positions:type_name -> com.floolishman.guider.params.GuiderPosition
	0, // 3: com.floolishman.guider.service.GuiderWatcher.GetItems:input_type -> com.floolishman.guider.service.GetItemsReq
	2, // 4: com.floolishman.guider.service.GuiderWatcher.GetSymbolConfig:input_type -> com.floolishman.guider.service.GetSymbolConfigReq
	4, // 5: com.floolishman.guider.service.GuiderWatcher.GetPositions:input_type -> com.floolishman.guider.service.GetPositionReq
	9, // 6: com.floolishman.guider.service.GuiderWatcher.GetAllPositions:input_type -> google.protobuf.Empty
	1, // 7: com.floolishman.guider.service.GuiderWatcher.GetItems:output_type -> com.floolishman.guider.service.GetItemResp
	3, // 8: com.floolishman.guider.service.GuiderWatcher.GetSymbolConfig:output_type -> com.floolishman.guider.service.GetSymbolConfigResp
	5, // 9: com.floolishman.guider.service.GuiderWatcher.GetPositions:output_type -> com.floolishman.guider.service.GetPositionResp
	5, // 10: com.floolishman.guider.service.GuiderWatcher.GetAllPositions:output_type -> com.floolishman.guider.service.GetPositionResp
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_params_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetItemsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetItemResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSymbolConfigReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSymbolConfigResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPositionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPositionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_rawDesc = nil
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GuiderWatcherClient is the client API for GuiderWatcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GuiderWatcherClient interface {
	// 通过account 获取指定配置下的跟单员列表信息
	GetItems(ctx context.Context, in *GetItemsReq, opts ...grpc.CallOption) (*GetItemResp, error)
	// 根据指定账号及portfolioId获取交易对配置
	GetSymbolConfig(ctx context.Context, in *GetSymbolConfigReq, opts ...grpc.CallOption) (*GetSymbolConfigResp, error)
	// 根据指定portfolioId获取当前positions
	GetPositions(ctx context.Context, in *GetPositionReq, opts ...grpc.CallOption) (*GetPositionResp, error)
	// 获取所有当前可用仓位
	GetAllPositions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetPositionResp, error)
}

type guiderWatcherClient struct {
	cc grpc.ClientConnInterface
}

func NewGuiderWatcherClient(cc grpc.ClientConnInterface) GuiderWatcherClient {
	return &guiderWatcherClient{cc}
}

func (c *guiderWatcherClient) GetItems(ctx context.Context, in *GetItemsReq, opts ...grpc.CallOption) (*GetItemResp, error) {
	out := new(GetItemResp)
	err := c.cc.Invoke(ctx, "/com.floolishman.guider.service.GuiderWatcher/GetItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guiderWatcherClient) GetSymbolConfig(ctx context.Context, in *GetSymbolConfigReq, opts ...grpc.CallOption) (*GetSymbolConfigResp, error) {
	out := new(GetSymbolConfigResp)
	err := c.cc.Invoke(ctx, "/com.floolishman.guider.service.GuiderWatcher/GetSymbolConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guiderWatcherClient) GetPositions(ctx context.Context, in *GetPositionReq, opts ...grpc.CallOption) (*GetPositionResp, error) {
	out := new(GetPositionResp)
	err := c.cc.Invoke(ctx, "/com.floolishman.guider.service.GuiderWatcher/GetPositions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guiderWatcherClient) GetAllPositions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetPositionResp, error) {
	out := new(GetPositionResp)
	err := c.cc.Invoke(ctx, "/com.floolishman.guider.service.GuiderWatcher/GetAllPositions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuiderWatcherServer is the server API for GuiderWatcher service.
type GuiderWatcherServer interface {
	// 通过account 获取指定配置下的跟单员列表信息
	GetItems(context.Context, *GetItemsReq) (*GetItemResp, error)
	// 根据指定账号及portfolioId获取交易对配置
	GetSymbolConfig(context.Context, *GetSymbolConfigReq) (*GetSymbolConfigResp, error)
	// 根据指定portfolioId获取当前positions
	GetPositions(context.Context, *GetPositionReq) (*GetPositionResp, error)
	// 获取所有当前可用仓位
	GetAllPositions(context.Context, *emptypb.Empty) (*GetPositionResp, error)
}

// UnimplementedGuiderWatcherServer can be embedded to have forward compatible implementations.
type UnimplementedGuiderWatcherServer struct {
}

func (*UnimplementedGuiderWatcherServer) GetItems(context.Context, *GetItemsReq) (*GetItemResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItems not implemented")
}
func (*UnimplementedGuiderWatcherServer) GetSymbolConfig(context.Context, *GetSymbolConfigReq) (*GetSymbolConfigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSymbolConfig not implemented")
}
func (*UnimplementedGuiderWatcherServer) GetPositions(context.Context, *GetPositionReq) (*GetPositionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPositions not implemented")
}
func (*UnimplementedGuiderWatcherServer) GetAllPositions(context.Context, *emptypb.Empty) (*GetPositionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllPositions not implemented")
}

func RegisterGuiderWatcherServer(s *grpc.Server, srv GuiderWatcherServer) {
	s.RegisterService(&_GuiderWatcher_serviceDesc, srv)
}

func _GuiderWatcher_GetItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuiderWatcherServer).GetItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.floolishman.guider.service.GuiderWatcher/GetItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuiderWatcherServer).GetItems(ctx, req.(*GetItemsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuiderWatcher_GetSymbolConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSymbolConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuiderWatcherServer).GetSymbolConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.floolishman.guider.service.GuiderWatcher/GetSymbolConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuiderWatcherServer).GetSymbolConfig(ctx, req.(*GetSymbolConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuiderWatcher_GetPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPositionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuiderWatcherServer).GetPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.floolishman.guider.service.GuiderWatcher/GetPositions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuiderWatcherServer).GetPositions(ctx, req.(*GetPositionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuiderWatcher_GetAllPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuiderWatcherServer).GetAllPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.floolishman.guider.service.GuiderWatcher/GetAllPositions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuiderWatcherServer).GetAllPositions(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _GuiderWatcher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.floolishman.guider.service.GuiderWatcher",
	HandlerType: (*GuiderWatcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetItems",
			Handler:    _GuiderWatcher_GetItems_Handler,
		},
		{
			MethodName: "GetSymbolConfig",
			Handler:    _GuiderWatcher_GetSymbolConfig_Handler,
		},
		{
			MethodName: "GetPositions",
			Handler:    _GuiderWatcher_GetPositions_Handler,
		},
		{
			MethodName: "GetAllPositions",
			Handler:    _GuiderWatcher_GetAllPositions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
