# 运行模式
mode: online
# 交易对配置
pairs:
  # 交易对名称
  ETHUSDT:
    # 状态
    status: true
    # 杠杆倍数 需要带上小数点
    leverage: 100.0
    # 仓位模式
    marginType: CROSSED
    # 保证金模式 ROLL 滚仓｜STATIC 静态
    marginMode: STATIC
    # 保证金开仓金额 ROLL模式下为比例 ｜ STATIC 为数量
    marginSize: 0.008
    # 最大网格间距
    maxGridStep: 9.0
    # 最小网格间距
    minGridStep: 8.0
    # 网格空窗期
    windowPeriod: 8.5
    # 最大加仓次数
    maxAddPosition: 4
    # 最小加仓次数
    minAddPosition: 3
    # 价格波动触发限制 eth 3 $/s    btc 150 $/s
    undulatePriceLimit: 5.0
    # 价格波动触发限制 eth 100 Vol/s  btc 30 Vol/s
    undulateVolumeLimit: 100.0
    # 移动止盈后撤比例
    profitableScale: 0.1
    # 移动止盈后撤比例-step
    profitableScaleDecrStep: 0.005
    # 触发移动止损比例
    profitableTrigger: 0.185
    # 触发移动止损比例-step
    profitableTriggerIncrStep: 0.04
    # 最大加仓后联合仓位亏损拉回比例
    pullMarginLossRatio: 0.18
    # 最大保证金比例
    maxMarginRatio: 0.40
    # 最大止损保证金比例
    maxMarginLossRatio: 0.0038
  # 交易对名称
  BTCUSDT:
    # 状态
    status: true
    # 杠杆倍数 需要带上小数点
    leverage: 100.0
    # 仓位模式
    marginType: CROSSED
    # 保证金模式 ROLL 滚仓｜STATIC 静态
    marginMode: STATIC
    # 保证金开仓金额 ROLL模式下为比例 ｜ STATIC 为数量
    marginSize: 0.002
    # 最大网格间距
    maxGridStep: 150.0
    # 最小网格间距
    minGridStep: 120.0
    # 网格空窗期
    windowPeriod: 120.0
    # 最大加仓次数
    maxAddPosition: 4
    # 最小加仓次数
    minAddPosition: 3
    # 价格波动触发限制 eth 3 $/s    btc 150 $/s
    undulatePriceLimit: 150.0
    # 价格波动触发限制 eth 100 Vol/s  btc 25 Vol/s
    undulateVolumeLimit: 25.0
    # 移动止盈后撤比例
    profitableScale: 0.1
    # 移动止盈后撤比例-step
    profitableScaleDecrStep: 0.005
    # 触发移动止损比例
    profitableTrigger: 0.185
    # 触发移动止损比例-step
    profitableTriggerIncrStep: 0.04
    # 最大加仓后联合仓位亏损拉回比例
    pullMarginLossRatio: 0.18
    # 最大保证金比例
    maxMarginRatio: 0.40
    # 最大止损保证金比例
    maxMarginLossRatio: 0.0038
# 看门狗服务grpc地址
watchdog:
  host: "127.0.0.1:9999"
# 策略配置
strategies:
  - "Grid1h"
# 量化caller配置
caller:
  # 执行模式 grid | frequency | dual | candle | interval | watchdog
  checkMode: grid
  # watchdog模式下是否是跟随模式，其他模式下都为false
  followSymbol: false
  # 时间止损市场 单位分钟
  lossTimeDuration: 40
# db存储位置
storage:
  driver: sqlite
  path: "runtime/data/floolishman.db"
# binance api key 密钥
api:
  encrypt: ED25519
  key: ""
  secret: ""
  pem: ""
# telegram配置
telegram:
  token: ""
  user: ""
