# 运行模式
mode: online
# 看门狗服务grpc地址
watchdog:
  host: "127.0.0.1:9999"
# 策略配置
strategies:
  #  - Emacross15m
  #  - Range15m
  #  - Momentum15m
  #  - MomentumVolume15m
  #  - Rsi15m
  #  - Vibrate15m
  #  - Kc15m
  #  - Rsi15m
  #  - Macd15m
  #  - "Grid1h"
  #  - "Resonance15m"
  #  - "Radicalization"
  - "Scooper"
# 量化caller配置
caller:
  # 执行模式 grid | frequency | dual | candle | interval | watchdog | scoop
  checkMode: candle
  # 忽略开单时段
  ignoreHours:
  # - 2
  # - 19
  # - 20
  #    - 21
  # - 22
  # 忽略币种
  ignorePairs:
    - BTCUSDT
    - ETHUSDT
    - BNBUSDT
    - SOLUSDT
    - BCHUSDT
    - YFIUSDT
  # watchdog模式下是否是跟随模式，其他模式下都为false
  followSymbol: false
  # 时间止损市场 单位分钟
  lossTimeDuration: 60
  # ---------- 通用配置 --------------
  # 杠杆倍数
  leverage: 20.0
  # 仓位模式
  marginType: CROSSED
  # 保证金模式 ROLL 滚仓｜STATIC 静态 | | MARGIN 保证金
  marginMode: MARGIN
  # 保证金开仓金额 ROLL模式下为比例 ｜ STATIC 为数量 | MARGIN 为USDT
  marginSize: 150.0
  # 移动止盈后撤比例
  profitableScale: 0.0015
  # 移动止盈后撤比例-step 0.000125
  profitableScaleDecrStep: 0.00025
  # 触发移动止损比例
  profitableTrigger: 0.0075
  # 触发移动止损比例-step
  profitableTriggerIncrStep: 0.001
  # 最大加仓后联合仓位亏损拉回比例
  pullMarginLossRatio: 0.0018
  # 最大保证金比例
  maxMarginRatio: 0.0040
  # 最大止损保证金比例 0.005 为0：atr止损
  maxMarginLossRatio: 0.0035
  # 暂停交易时常（分钟）
  pauseCaller: 45
# db存储位置
storage:
  driver: sqlite
  path: "runtime/data/floolishman.db"
# binance api key 密钥
api:
  encrypt: ED25519
  key: ""
  secret: ""
  pem: ""
# telegram配置
telegram:
  token: ""
  user: ""
